import type { Metadata } from "next";
import "./globals.css";
<<<<<<< HEAD
import Header from "./(components)/Header/Header";
=======
import Header from "./(componentes)/Header/Header";
import Footer from "../components/Footer/Footer"
>>>>>>> 4b9b7dcd18e8e2cfb6d83fb135f680ed513b2114

import { Merriweather, Poppins } from "next/font/google";


// Headings font
const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"], 
});

// Paragraphs font
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merriweather.variable} ${poppins.variable} font-sans antialiased w-full`}
      >
      
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
