import type { Metadata } from "next";
import "./globals.css";
import AOSWrapper from "@/components/AosWrapper";
import ProfileChecker from "@/components/ProfileChecker";
import { ClerkProvider } from "@clerk/nextjs";

import { Merriweather, Poppins } from "next/font/google";

import LayoutWrapper from "@/components/Dashboard/LayoutWrapper";

// Headings font
const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
});

// Paragraphs font
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${merriweather.variable} ${poppins.variable} font-sans antialiased w-full bg-[#F1F5F9]`}
          suppressHydrationWarning
        >
          <ProfileChecker>
            <AOSWrapper />
            <LayoutWrapper>{children}</LayoutWrapper>
          </ProfileChecker>
        </body>
      </html>
    </ClerkProvider>
  );
}
