import type { Metadata } from "next";
import "./globals.css";
import Footer from "../components/Footer/Footer";
import AOSWrapper from "@/components/AosWrapper";
import Header from "@/components/Header/Header";
import ProfileChecker from "@/components/ProfileChecker";
import { ClerkProvider } from "@clerk/nextjs";

import { Merriweather, Poppins } from "next/font/google";

// Headings font
const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
});

// Paragraphs font
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${merriweather.variable} ${poppins.variable} font-sans antialiased w-full bg-[#F1F5F9]`}
        >
          
          <AOSWrapper />
          <Header />
          <ProfileChecker>
            <main className="w-full">{children}</main>
          
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
